# Generated by Django 2.2.5 on 2022-04-06 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20220406_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hosts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
